avatar:
  url: https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic1.zhimg.com%2F80%2Fv2-6419c5565ab345fb3cd2b4f18492b636_720w.jpg%3Fsource%3D1940ef5c&refer=http%3A%2F%2Fpic1.zhimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1646936736&t=4419a04597d5da9fbaed2476020a3eae

banner:
  enable: true
  title: 王先生
  subtitle: 相逢拌酩酊,何必备芳鲜。
  description: 少年去游荡,中年想掘藏,老来当和尚。
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line
    
mode: auto

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  dark_bg_image: xxx
  # placeholder:


favicon: https://s3.bmp.ovh/imgs/2022/03/5194728442e7a532.jpg

social:
  - name: GitHub
    link: https://github.com/logicwang
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:me@yunyoujun.cn
    icon: icon-mail-line
    color: "#8E71C1"
  - name: 网易云音乐
    link: https://music.163.com/#/my/m/music/playlist?id=867800107
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
  - name: 知乎
    link: https://www.zhihu.com/people/peng-yu-yan-44-15
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: 哔哩哔哩
    link: https://space.bilibili.com/474868654?spm_id_from=333.1007.0.0
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Twitter
    link: https://twitter.com/logicwyf
    icon: icon-twitter-line
    color: "#1da1f2"

footer:
  live_time:
    enable: true
    prefix: 本博客已运行
    start_time: "2022-02-09T00:25:00"

girls:
  enable: true

pages:
  - name: 二次元
    url: /girls/
    icon: icon-genderless-line
    color: dodgerblue

tags:
  HTML5/CSS3: crimson
  Hexo: orange
  Javascript: "#21374b"
  Linux: saddlebrown
  Macos: crimson
  Markdown: royalblue
  Vue: dimgray
  brew: "#0078e7"
  github: mediumpurple
  npm: "#d04d2d"
  实例: "#2577b1"

engine_search:
  enable: false

local_search:
  enable: true

highlight:
  enable: true
# 启用 prism
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ""

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

  footer:
  powered: false
  enable: false

wordcloud:
  enable: false
  height: 350

disqus:
  enable: true
  shortname: logicwang
  count: true

reward:
  enable: true
  icon: icon-hand-coin-line
  comment: can you give me money?
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: 微信支付
      path: https://tva1.sinaimg.cn/large/0074R88yly8gzgttvq9tqj30aq0amwf7.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 19
  
bg_image:
  enable: true
  url: https://i.bmp.ovh/imgs/2022/04/04/797720935637f277.png
  dark: https://i.bmp.ovh/imgs/2022/04/04/797720935637f277.png
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

minivaline:
  enable: true
  md: true
  # 更多选项 https://minivaline.js.org/docs/cn/#/Options 按照yml格式继续填写即可 （除了 [el] 选项）
  # emoticonUrl 等列表选项 可参考 https://github.com/MiniValine/hexo-next-minivaline
  # 下面是一个例子：
  backend: waline
  serverURL: https://waline.vercel.app

creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow