avatar:
  url: https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic1.zhimg.com%2F80%2Fv2-6419c5565ab345fb3cd2b4f18492b636_720w.jpg%3Fsource%3D1940ef5c&refer=http%3A%2F%2Fpic1.zhimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1646936736&t=4419a04597d5da9fbaed2476020a3eae

banner:
  enable: true
  title: 王先生
  subtitle: 相逢拌酩酊,何必备芳鲜。
  description: 少年去游荡,中年想掘藏,老来当和尚。
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line
    
mode: auto

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  dark_bg_image: xxx
  # placeholder:


favicon: https://tva1.sinaimg.cn/large/0074R88yly8h1o7mey550j30ku0dwwgh.jpg


social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/YunYouJun
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:me@yunyoujun.cn
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 微博
    link: https://weibo.com/jizhideyunyoujun
    icon: ri:weibo-line
    color: '#E6162D'
  - name: 豆瓣
    link: https://www.douban.com/people/yunyoujun/
    icon: ri:douban-line
    color: '#007722'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=247102977
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 知乎
    link: https://www.zhihu.com/people/yunyoujun/
    icon: ri:zhihu-line
    color: '#0084FF'
  - name: 哔哩哔哩动画
    link: https://space.bilibili.com/1579790
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: 微信公众号
    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
    icon: ri:wechat-2-line
    color: '#1AAD19'
  - name: Twitter
    link: https://twitter.com/YunYouJun
    icon: ri:twitter-line
    color: '#1da1f2'
  - name: Telegram
    link: https://t.me/YunYouJun
    icon: ri:telegram-line
    color: '#0088CC'
  - name: Telegram Channel
    link: https://t.me/elpsycn
    icon: ri:telegram-fill
    color: '#0088CC'
  - name: Travelling
    link: https://travellings.link
    icon: ri:gitee-line
    color: black

head:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css


footer:
  live_time:
    enable: true
    prefix: 本博客已运行
    start_time: "2022-02-09T00:25:00"

girls:
  enable: true

pages:
  - name: 二次元
    url: /girls/
    icon: icon-genderless-line
    color: dodgerblue

tags:
  HTML5/CSS3: crimson
  Hexo: orange
  Javascript: "#21374b"
  Linux: saddlebrown
  Macos: crimson
  Markdown: royalblue
  Vue: dimgray
  brew: "#0078e7"
  github: mediumpurple
  npm: "#d04d2d"
  实例: "#2577b1"

engine_search:
  enable: false

local_search:
  enable: true

highlight:
  enable: true
# 启用 prism
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ""

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

  footer:
  powered: false
  enable: false

wordcloud:
  enable: false
  height: 350

reward:
  enable: false
  icon: icon-hand-coin-line
  comment: can you give me money?
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: 微信支付
      path: https://tva1.sinaimg.cn/large/0074R88yly8gzgttvq9tqj30aq0amwf7.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 28
      
bg_image:
  enable: true
  url: https://tva1.sinaimg.cn/large/0074R88yly8h1o677t2y2j31400px441.jpg
  dark: https://tva1.sinaimg.cn/large/0074R88yly8h1o677t2y2j31400px441.jpg
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

cdn:
  pre: ''
  css: 
    ionicons: https://cdn.jsdelivr.net/npm/ionicons/dist/css/ionicons.min.css
  js:
    base:
      - xxx
    async:
      # 默认引入的图标资源，使用 iconfont
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer: